name: productive_families
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  path_provider: ^2.0.15
  flutter_slidable: ^3.0.0
  animated_bottom_navigation_bar: ^0.3.2
  flutter_snake_navigationbar: ^0.6.0
  like_button: ^2.0.4
  anim_search_bar: ^2.0.2
  sliding_up_panel: ^2.0.0+1
  flutter_loadingindicator: ^1.0.1
  flutter_svg: ^2.0.9
  get_it: ^7.2.0
  firebase_messaging: ^14.7.15
  shared_preferences: ^2.1.0
  fluttertoast: ^8.2.4
  rename_app: ^1.3.1  
  flutter_launcher_icons: ^0.13.1
  firebase_auth: ^4.7.1
  firebase_database: ^10.4.6
  cloud_firestore: ^4.15.5
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.5
  shimmer: ^2.0.0
  carousel_slider: ^4.2.1
  awesome_notifications: ^0.8.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/new_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/user/

  fonts:
    - family: dancing_script
      fonts:
        - asset: assets/fonts/dancing_script.ttf

# dependency_overrides:
#   firebase_core_platform_interface: 4.5.1